name: Deploy to k3s

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Authenticate to k3s cluster
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "${KUBECONFIG}" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml

    - name: Apply Kubernetes manifests
      run: kubectl apply -f nginx-hello-world.yml

    - name: Port-forward nginx service
      run: nohup kubectl port-forward svc/nginx-hello-world 8080:80 > port-forward.log 2>&1 &

